[package]
name = "sv"
version = "0.1.0"
authors = ["Jason Ma <jasonma5501@gmail.com>"]
edition = "2018"

[dependencies]
native-windows-gui = "1.0.12"
native-windows-derive = "1.0.3"

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]